<?php
namespace App\Common;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Config;

class FcmNotification{
    public static function fcmPushNotification($firebaseToken, $title, $body)
    {
        //$SERVER_API_KEY = env('FCM_SERVER_KEY');

        $SERVER_API_KEY = Config::get('constants.firebase_server_key');

        $data = [
            "to" => $firebaseToken,
            "notification" => [
                "title" => $title,
                "body" => $body,
            ]
        ];
        $dataString = json_encode($data);

        $headers = [
            'Authorization: key=' . $SERVER_API_KEY,
            'Content-Type: application/json',
        ];

        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $dataString);

        $response = curl_exec($ch);

        return back()->with('success', 'Notification send successfully.');


        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        // $ch = curl_init();

        // curl_setopt($ch, CURLOPT_URL, 'https://fcm.googleapis.com/v1/projects/myproject-b5ae1/messages:send');
        // curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        // curl_setopt($ch, CURLOPT_POST, 1);
        // curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n\"message\":{\n   \"notification\":{\n     \"title\":\"FCM Message\",\n     \"body\":\"This is an FCM Message\"\n   },\n   \"token\":\"bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...\"\n}}");

        // $headers = array();
        // $headers[] = 'Authorization: Bearer ya29.ElqKBGN2Ri_Uz...HnS_uNreA';
        // $headers[] = 'Content-Type: application/json';
        // curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        // $result = curl_exec($ch);
        // if (curl_errno($ch)) {
        //     echo 'Error:' . curl_error($ch);
        // }
        // curl_close($ch);
    }
}
?>
